### ISSUE TITLE
Update the code base for wio 2.0

### ISSUE THREAD

**Issue by dhillondeep** [waterloop/goose-sensors-wio#12]
* `url` is replaced with `repository`
    * In terms of what to add for repository, it should be the url of each sensor. ex: https://github.com/waterloop/goose-sensors-wio/tree/master/bsi0007-tilt-sensor
* `pkg_compile_flags` added

* Dmytro remove yourself from contributors because you are already an author
* For the author field, add more information so you can be linked to the project properly:
    * https://docs.npmjs.com/files/package.json#people-fields-author-contributors
    * Make it one line like:
       "Deep Dhillon <<deep@deepdhillon.ca>> (http://github.com/dhillondeep)"

**Comment by dshynkev** [comment]
Should `wio.yml` files in the tree also be update-invariant? For example, whenever I run `wio update pkg .`, double quotes are stripped from strings. Would it be better to commit them in this state so that `wio update` doesn't change `wio.yml` when run on a freshly cloned repo (prerequisite to build)?

**Comment by Mogball** [comment]
if update-invariant means wio is backwards compatible, I agree

otherwise I think it's whatever go package `wio` is using to read and write yaml files; it reads in the format we're used to and prints in the "preferred" yaml format

**Comment by Mogball** [comment]
idk why I clicked cose

**Comment by dhillondeep** [comment]
Yeah, so multiple times `wio.yml` file has to be read and written and hence it changes the format to default yaml format
